### ISSUE TITLE
makeAction() waits forever

### ISSUE THREAD

**Issue by Ohsaworks** [Farama-Foundation/ViZDoom#261] opened 2017-10-13 14:31 UTC
The function "DoomGame::makeAction()" suddenly stalls after several (100-500) steps performed.
I guess there is something infinite loop in advanceAction() such as WaitForDoomWork() while makeAction is performing.
https://github.com/mwydmuch/ViZDoom/blob/6232e1770d1ae78a8da66e2fc7ceaa0278c982cb/src/lib/ViZDoomGame.cpp#L160
https://github.com/mwydmuch/ViZDoom/blob/f8fc04e8590ffa7cb500e1dbfbdecb6ffdcf3f9d/src/lib/ViZDoomController.cpp#L1060

But I don't know exactly what is the problem.

Here is the description of my implementation:
- Python 3
- Multi-agent environment (two agents connect to a same environment simultaneously)
- RepeatFrames >= 3 (somehow it works if RepeatFrames <= 2)
- Health = 100% (perhaps, death is not a reason for stopping)

Does anyone have any idea for a solution?

**Comment by wjaskowski** [comment] 2017-10-13 15:13
Any code to reproduce?

**Comment by Ohsaworks** [comment] 2017-10-14 02:44
Sure. Here is the code to reproduce:
https://gist.github.com/Ohsaworks/90407ffb015fd06f243b2c8222c94aab

The code is on a setting as same as the one which I mentioned in the issue above.

- Python 3
- Multi-agent environment (two agents connect to a same environment simultaneously)
- RepeatFrames >= 3 (somehow it works if RepeatFrames <= 2)
- Health = 100% (perhaps, death is not a reason for stopping)

So, you can run it on python3. For example:
`$ python3 template_multi.py`

Then get:
```
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
Press 'Q' to abort network game synchronization.
Contacting host: /AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
Press 'Q' to abort network game synchronization.
Got connect from node 1.                
Waiting for players: .. [ 2/ 2]
Sending all here.                       

Total players: 2                        

Waiting for other players: .. [ 2/ 2]
Console player number: 1                
Received All Here, sending ACK.         

Go                                      
Total players: 2                        

Console player number: 1                
Received All Here, sending ACK.         
Received "Go."                          

Total players: 2                        

Found Player1 (node 1, player 1)        
Found Player2 (node 1, player 2)        
Found Player2 (node 0, player 2)        




Episode #1
piyo 10
host before
hoge 10
guest before
host after
(...never awake...)
^CTraceback (most recent call last):
  File "template_multi.py", line 114, in <module>
    host_player()
  File "template_multi.py", line 62, in host_player
    game.make_action(choice(actions), frame_repeat)
vizdoom.vizdoom.SignalException: Signal SIGINT received. ViZDoom instance has been closed.
```
As you can see, the code stalls in `game.make_action`. 
This is why I have speculation that makeAction stops.

The issue somehow depends on a parameter `RepeatFrame`.
Though I set the `RepeatFrame = 10` (line 11) in the code,
you can also confirm the issue won't appear if `RepeatFrame = 2`.
Please try to make sure the issue occurs by running the code.

**Comment by Miffyli** [comment] 2017-10-16 09:07
Just pitching in that it indeed gets stuck in same for me (Ubuntu 16.04, VizDoom 1.1.4, Python 3.5), but using `ASYNC_PLAYER` seems to work (albeit it is not too good for training). This seems very related to #228 .

(PS: You might want to use scenarios designed for multiplayer/deathmatch, such as "cig.cfg", just to make sure it is not the config/scenario breaking things up :) )

**Comment by jkterry1** [comment] 2024-10-07 19:35
Hey,

I'm going to close this issue since there haven't been any new updates ~8 years. If anyone has this bug again, please reply here or create a new issue :)

**Closed by jkterry1** 2024-10-07 19:35 UTC
